# Создаем таблицу
CREATE TABLE TESTDB.CURRENCY
(
    ID        INT        NOT NULL AUTO_INCREMENT,
    OPERATION VARCHAR(5) NOT NULL,
    CCY       VARCHAR(3) NOT NULL,
    SUMM      BOOLEAN    NOT NULL,
    EKV       BOOLEAN    NOT NULL,
    PRIMARY KEY (ID)
);

# Наполняем таблицу демо данными
INSERT INTO TESTDB.CURRENCY (ID, OPERATION, CCY, SUMM, EKV)
VALUES ('1', 'buy', 'EUR', '300', 11940);
INSERT INTO TESTDB.CURRENCY (ID, OPERATION, CCY, SUMM, EKV)
VALUES ('2', 'sale', 'EUR', '200', 8160);
INSERT INTO TESTDB.CURRENCY (ID, OPERATION, CCY, SUMM, EKV)
VALUES ('3', 'buy', 'USD', '150', 5685);
INSERT INTO TESTDB.CURRENCY (ID, OPERATION, CCY, SUMM, EKV)
VALUES ('4', 'buy', 'USD', '250', 9475);
INSERT INTO TESTDB.CURRENCY (ID, OPERATION, CCY, SUMM, EKV)
VALUES ('5', 'sale', 'USD', '350', 13440);
INSERT INTO TESTDB.CURRENCY (ID, OPERATION, CCY, SUMM, EKV)
VALUES ('6', 'buy', 'USD', '300', 11370);

# Смотрим результат
SELECT *
from TESTDB.BOOKS;